remove the check for success test from github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,13 +27,13 @@ jobs:
       # - name: Run chromedriver
       #   run: .\chromedriver.exe --port=4444 --disable-gpu
         
-      - name: Check for success test
-        run: |
-          if grep -q "All tests passed!" integration_test/test_results.json; then
-            echo "Success test: All tests passed!"
-          else
-            echo "Error test: Tests failed."
-            exit 1
-          fi
+      # - name: Check for success test
+      #   run: |
+      #     if grep -q "All tests passed!" integration_test/test_results.json; then
+      #       echo "Success test: All tests passed!"
+      #     else
+      #       echo "Error test: Tests failed."
+      #       exit 1
+      #     fi
 
       
